package issuetracker.entity;

import lombok.*;

import javax.persistence.*;
import java.io.Serializable;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@MappedSuperclass
@ToString(doNotUseGetters = true) //for displaying and logging
class BaseEntity implements Serializable {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) //ids are generated by the JPA provider(mysql, oracle etc.)
    @Column
    private int id;
}
