package issuetracker.entity;

import lombok.*;

import javax.persistence.*;
import java.io.Serializable;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@MappedSuperclass
@ToString(doNotUseGetters = true)
class BaseEntity implements Serializable {
    /**
     * ids are generated by the JPA provider(mysql, oracle etc.)
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column
    private int id;
}
